name: Publish pages
on:
  push:
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install and Build
        run: |
          npm install
          npm run build
          touch out/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.2
        with:
          branch: gh-pages
          folder: out
